[package]
name = "quickstep"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An open source Bf-tree implementation"
homepage = "https://github.com/raphaeldarley/quickstip"
repository = "https://github.com/raphaeldarley/quickstep"

[dependencies]
